Document: okasaki
Title: Debian okasaki Manual
Author: <insert document author here>
Abstract: This manual describes what okasaki is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/okasaki/okasaki.sgml.gz

Format: postscript
Files: /usr/share/doc/okasaki/okasaki.ps.gz

Format: text
Files: /usr/share/doc/okasaki/okasaki.text.gz

Format: HTML
Index: /usr/share/doc/okasaki/html/index.html
Files: /usr/share/doc/okasaki/html/*.html
